// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieWorld.Models;

public partial class GenreTranslation
{
    public int GenreId { get; set; }

    public string LanguageCode { get; set; }

    public string Name { get; set; }

    public virtual Genre Genre { get; set; }

    public virtual LanguageCode LanguageCodeNavigation { get; set; }
}