// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieWorld.Models;

public partial class MoviePerson
{
    public int PersonId { get; set; }

    public int MovieId { get; set; }

    public string Role { get; set; }

    public virtual Movie Movie { get; set; }

    public virtual Person Person { get; set; }
}