// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieWorld.Models;

#nullable disable

namespace MovieWorld.Migrations
{
    [DbContext(typeof(TrainingBrattiContext))]
    partial class TrainingBrattiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");

            modelBuilder.Entity("MovieWorld.Models.Chart", b =>
                {
                    b.Property<int>("ChartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Chart_ID");

                    b.Property<DateTime?>("CreationData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("(datetime('now'))");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("User_ID");

                    b.HasKey("ChartId")
                        .HasName("PK__Chart__314712152BEAFB54");

                    b.HasIndex("UserId");

                    b.ToTable("Chart", (string)null);
                });

            modelBuilder.Entity("MovieWorld.Models.ChartItem", b =>
                {
                    b.Property<int>("ChartId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Chart_ID");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Movie_ID");

                    b.Property<int?>("Quantità")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChartId", "MovieId")
                        .HasName("PK__ChartIte__76EF9255BF58DFA4");

                    b.HasIndex("MovieId");

                    b.ToTable("ChartItem", (string)null);
                });

            modelBuilder.Entity("MovieWorld.Models.Format", b =>
                {
                    b.Property<int>("FormatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Format_ID");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("FormatId")
                        .HasName("PK__Format__C66EB6DCC5873E6B");

                    b.ToTable("Format", (string)null);
                });

            modelBuilder.Entity("MovieWorld.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Genre_ID");

                    b.HasKey("GenreId")
                        .HasName("PK__Genre__964A20062CDBCC18");

                    b.ToTable("Genre", (string)null);
                });

            modelBuilder.Entity("MovieWorld.Models.GenreTranslation", b =>
                {
                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Genre_ID");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("GenreId", "LanguageCode")
                        .HasName("PK__GenreTra__DEF2E8A5963F4BE9");

                    b.HasIndex("LanguageCode");

                    b.ToTable("GenreTranslation", (string)null);
                });

            modelBuilder.Entity("MovieWorld.Models.LanguageCode", b =>
                {
                    b.Property<string>("LanguageCode1")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("LanguageCode");

                    b.HasKey("LanguageCode1")
                        .HasName("PK__Language__8B8C8A3513DDEABF");

                    b.ToTable("LanguageCode", (string)null);
                });

            modelBuilder.Entity("MovieWorld.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Movie_ID");

                    b.Property<decimal?>("Cost")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("FormatId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Format_ID");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsCult")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrailerUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("TrailerURL");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId")
                        .HasName("PK__Movie__7A8804053452EFE6");

                    b.HasIndex("FormatId");

                    b.ToTable("Movie", (string)null);
                });

            modelBuilder.Entity("MovieWorld.Models.MovieGenre", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Movie_ID");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Genre_ID");

                    b.HasKey("MovieId", "GenreId")
                        .HasName("PK_MovieGenre");

                    b.HasIndex("GenreId");

                    b.ToTable("MovieGenre", (string)null);
                });

            modelBuilder.Entity("MovieWorld.Models.MoviePerson", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Person_ID");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Movie_ID");

                    b.Property<string>("Role")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId", "MovieId")
                        .HasName("PK__MoviePer__390350CBFE68D7D3");

                    b.HasIndex("MovieId");

                    b.ToTable("MoviePerson", (string)null);
                });

            modelBuilder.Entity("MovieWorld.Models.MovieSellPoint", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Movie_ID");

                    b.Property<int>("SellPointId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SellPoint_ID");

                    b.Property<int?>("Quantità")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId", "SellPointId")
                        .HasName("PK__MovieSel__8373B2F0EC6ADF7F");

                    b.HasIndex("SellPointId");

                    b.ToTable("MovieSellPoint", (string)null);
                });

            modelBuilder.Entity("MovieWorld.Models.MovieTranslation", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Movie_ID");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Story")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("MovieId", "LanguageCode")
                        .HasName("PK__MovieTra__3230CCA6FDAB878F");

                    b.HasIndex("LanguageCode");

                    b.ToTable("MovieTranslation", (string)null);
                });

            modelBuilder.Entity("MovieWorld.Models.News", b =>
                {
                    b.Property<int>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("News_ID");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.HasKey("NewsId")
                        .HasName("PK__News__DC88604BC91A20F8");

                    b.ToTable("News");
                });

            modelBuilder.Entity("MovieWorld.Models.NewsTranslation", b =>
                {
                    b.Property<int>("NewsId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("News_ID");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("NewsId", "LanguageCode")
                        .HasName("PK__NewsTran__9430A8E8C7DC8578");

                    b.HasIndex("LanguageCode");

                    b.ToTable("NewsTranslation", (string)null);
                });

            modelBuilder.Entity("MovieWorld.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Order_ID");

                    b.Property<DateTime?>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("(datetime('now'))");

                    b.Property<int>("OrderStateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OrderState_ID");

                    b.Property<int>("SellPointId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SellPoint_ID");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("User_ID");

                    b.HasKey("OrderId")
                        .HasName("PK__Order__F1E4639B5B959D7E");

                    b.HasIndex("OrderStateId");

                    b.HasIndex("SellPointId");

                    b.HasIndex("UserId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("MovieWorld.Models.OrderItem", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Movie_ID");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Order_ID");

                    b.Property<decimal>("PurchasedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("MovieId", "OrderId")
                        .HasName("PK__OrderIte__D596423C3691F457");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem", (string)null);
                });

            modelBuilder.Entity("MovieWorld.Models.OrderState", b =>
                {
                    b.Property<int>("OrderStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("OrderState_ID");

                    b.HasKey("OrderStateId")
                        .HasName("PK__OrderSta__FE9F9561BBF12A0D");

                    b.ToTable("OrderState", (string)null);
                });

            modelBuilder.Entity("MovieWorld.Models.OrderStateTranslation", b =>
                {
                    b.Property<int>("OrderStateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.HasKey("OrderStateId", "LanguageCode")
                        .HasName("PK__OrderSta__16C8D65E39A2DB81");

                    b.ToTable("OrderStateTranslation", (string)null);
                });

            modelBuilder.Entity("MovieWorld.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Person_ID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(datetime('now'))");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT")
                        .HasColumnName("imagePath");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId")
                        .HasName("PK__Person__7EABD08B29B36885");

                    b.ToTable("Person", (string)null);
                });

            modelBuilder.Entity("MovieWorld.Models.SellPoint", b =>
                {
                    b.Property<int>("SellPointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("SellPoint_ID");

                    b.Property<string>("Cap")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("CAP")
                        .IsFixedLength();

                    b.Property<double?>("Lat")
                        .HasColumnType("REAL");

                    b.Property<double?>("Lng")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.HasKey("SellPointId")
                        .HasName("PK__SellPoin__9FBB6F5EF441F108");

                    b.ToTable("SellPoint", (string)null);
                });

            modelBuilder.Entity("MovieWorld.Models.SellPointTranslation", b =>
                {
                    b.Property<int>("SellPointId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SellPoint_ID");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("SellPointId", "LanguageCode");

                    b.HasIndex("LanguageCode");

                    b.ToTable("SellPointTranslation", (string)null);
                });

            modelBuilder.Entity("MovieWorld.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("User_ID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(datetime('now'))");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("HashPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surname")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId")
                        .HasName("PK__User__206D9190B4E40C2D");

                    b.HasIndex(new[] { "Email" }, "UQ_User_Email")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("NewsMovie", b =>
                {
                    b.Property<int>("NewsId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("News_ID");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Movie_ID");

                    b.HasKey("NewsId", "MovieId")
                        .HasName("PK__NewsMovi__9B20E00B521A0AA0");

                    b.HasIndex("MovieId");

                    b.ToTable("NewsMovie", (string)null);
                });

            modelBuilder.Entity("NewsPerson", b =>
                {
                    b.Property<int>("NewsId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("News_ID");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Person_ID");

                    b.HasKey("NewsId", "PersonId")
                        .HasName("PK__NewsPers__7B62DD43E3464049");

                    b.HasIndex("PersonId");

                    b.ToTable("NewsPerson", (string)null);
                });

            modelBuilder.Entity("MovieWorld.Models.Chart", b =>
                {
                    b.HasOne("MovieWorld.Models.User", "User")
                        .WithMany("Charts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Chart__User_ID__37A5467C");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieWorld.Models.ChartItem", b =>
                {
                    b.HasOne("MovieWorld.Models.Chart", "Chart")
                        .WithMany("ChartItems")
                        .HasForeignKey("ChartId")
                        .IsRequired()
                        .HasConstraintName("FK__ChartItem__Chart__4CA06362");

                    b.HasOne("MovieWorld.Models.Movie", "Movie")
                        .WithMany("ChartItems")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChartItem__Movie__4D94879B");

                    b.Navigation("Chart");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieWorld.Models.GenreTranslation", b =>
                {
                    b.HasOne("MovieWorld.Models.Genre", "Genre")
                        .WithMany("GenreTranslations")
                        .HasForeignKey("GenreId")
                        .IsRequired()
                        .HasConstraintName("FK__GenreTran__Genre__48CFD27E");

                    b.HasOne("MovieWorld.Models.LanguageCode", "LanguageCodeNavigation")
                        .WithMany("GenreTranslations")
                        .HasForeignKey("LanguageCode")
                        .IsRequired()
                        .HasConstraintName("FK__GenreTran__Langu__49C3F6B7");

                    b.Navigation("Genre");

                    b.Navigation("LanguageCodeNavigation");
                });

            modelBuilder.Entity("MovieWorld.Models.Movie", b =>
                {
                    b.HasOne("MovieWorld.Models.Format", "Format")
                        .WithMany("Movies")
                        .HasForeignKey("FormatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Movie__Format_ID__33D4B598");

                    b.Navigation("Format");
                });

            modelBuilder.Entity("MovieWorld.Models.MovieGenre", b =>
                {
                    b.HasOne("MovieWorld.Models.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MovieGenre_Genre");

                    b.HasOne("MovieWorld.Models.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MovieGenre_Movie");

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieWorld.Models.MoviePerson", b =>
                {
                    b.HasOne("MovieWorld.Models.Movie", "Movie")
                        .WithMany("MoviePeople")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__MoviePers__Movie__45F365D3");

                    b.HasOne("MovieWorld.Models.Person", "Person")
                        .WithMany("MoviePeople")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__MoviePers__Perso__44FF419A");

                    b.Navigation("Movie");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MovieWorld.Models.MovieSellPoint", b =>
                {
                    b.HasOne("MovieWorld.Models.Movie", "Movie")
                        .WithMany("MovieSellPoints")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__MovieSell__Movie__5070F446");

                    b.HasOne("MovieWorld.Models.SellPoint", "SellPoint")
                        .WithMany("MovieSellPoints")
                        .HasForeignKey("SellPointId")
                        .IsRequired()
                        .HasConstraintName("FK__MovieSell__SellP__5165187F");

                    b.Navigation("Movie");

                    b.Navigation("SellPoint");
                });

            modelBuilder.Entity("MovieWorld.Models.MovieTranslation", b =>
                {
                    b.HasOne("MovieWorld.Models.LanguageCode", "LanguageCodeNavigation")
                        .WithMany("MovieTranslations")
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__MovieTran__Langu__4222D4EF");

                    b.HasOne("MovieWorld.Models.Movie", "Movie")
                        .WithMany("MovieTranslations")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__MovieTran__Movie__412EB0B6");

                    b.Navigation("LanguageCodeNavigation");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieWorld.Models.NewsTranslation", b =>
                {
                    b.HasOne("MovieWorld.Models.LanguageCode", "LanguageCodeNavigation")
                        .WithMany("NewsTranslations")
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__NewsTrans__Langu__5535A963");

                    b.HasOne("MovieWorld.Models.News", "News")
                        .WithMany("NewsTranslations")
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__NewsTrans__News___5441852A");

                    b.Navigation("LanguageCodeNavigation");

                    b.Navigation("News");
                });

            modelBuilder.Entity("MovieWorld.Models.Order", b =>
                {
                    b.HasOne("MovieWorld.Models.OrderState", "OrderState")
                        .WithMany("Orders")
                        .HasForeignKey("OrderStateId")
                        .IsRequired()
                        .HasConstraintName("FK__Order__OrderStat__3C69FB99");

                    b.HasOne("MovieWorld.Models.SellPoint", "SellPoint")
                        .WithMany("Orders")
                        .HasForeignKey("SellPointId")
                        .IsRequired()
                        .HasConstraintName("FK__Order__SellPoint__3E52440B");

                    b.HasOne("MovieWorld.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Order__User_ID__3D5E1FD2");

                    b.Navigation("OrderState");

                    b.Navigation("SellPoint");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieWorld.Models.OrderItem", b =>
                {
                    b.HasOne("MovieWorld.Models.Movie", "Movie")
                        .WithMany("OrderItems")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__OrderItem__Movie__7A672E12");

                    b.HasOne("MovieWorld.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__OrderItem__Order__7B5B524B");

                    b.Navigation("Movie");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MovieWorld.Models.OrderStateTranslation", b =>
                {
                    b.HasOne("MovieWorld.Models.OrderState", "OrderState")
                        .WithMany("OrderStateTranslations")
                        .HasForeignKey("OrderStateId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderStat__Order__01142BA1");

                    b.Navigation("OrderState");
                });

            modelBuilder.Entity("MovieWorld.Models.SellPointTranslation", b =>
                {
                    b.HasOne("MovieWorld.Models.LanguageCode", "LanguageCodeNavigation")
                        .WithMany("SellPointTranslations")
                        .HasForeignKey("LanguageCode")
                        .IsRequired()
                        .HasConstraintName("FK_SellPointTranslation_Language");

                    b.HasOne("MovieWorld.Models.SellPoint", "SellPoint")
                        .WithMany("SellPointTranslations")
                        .HasForeignKey("SellPointId")
                        .IsRequired()
                        .HasConstraintName("FK_SellPointTranslation_SellPoint");

                    b.Navigation("LanguageCodeNavigation");

                    b.Navigation("SellPoint");
                });

            modelBuilder.Entity("NewsMovie", b =>
                {
                    b.HasOne("MovieWorld.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__NewsMovie__Movie__59063A47");

                    b.HasOne("MovieWorld.Models.News", null)
                        .WithMany()
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__NewsMovie__News___5812160E");
                });

            modelBuilder.Entity("NewsPerson", b =>
                {
                    b.HasOne("MovieWorld.Models.News", null)
                        .WithMany()
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__NewsPerso__News___5BE2A6F2");

                    b.HasOne("MovieWorld.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__NewsPerso__Perso__5CD6CB2B");
                });

            modelBuilder.Entity("MovieWorld.Models.Chart", b =>
                {
                    b.Navigation("ChartItems");
                });

            modelBuilder.Entity("MovieWorld.Models.Format", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("MovieWorld.Models.Genre", b =>
                {
                    b.Navigation("GenreTranslations");

                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("MovieWorld.Models.LanguageCode", b =>
                {
                    b.Navigation("GenreTranslations");

                    b.Navigation("MovieTranslations");

                    b.Navigation("NewsTranslations");

                    b.Navigation("SellPointTranslations");
                });

            modelBuilder.Entity("MovieWorld.Models.Movie", b =>
                {
                    b.Navigation("ChartItems");

                    b.Navigation("MovieGenres");

                    b.Navigation("MoviePeople");

                    b.Navigation("MovieSellPoints");

                    b.Navigation("MovieTranslations");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("MovieWorld.Models.News", b =>
                {
                    b.Navigation("NewsTranslations");
                });

            modelBuilder.Entity("MovieWorld.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("MovieWorld.Models.OrderState", b =>
                {
                    b.Navigation("OrderStateTranslations");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MovieWorld.Models.Person", b =>
                {
                    b.Navigation("MoviePeople");
                });

            modelBuilder.Entity("MovieWorld.Models.SellPoint", b =>
                {
                    b.Navigation("MovieSellPoints");

                    b.Navigation("Orders");

                    b.Navigation("SellPointTranslations");
                });

            modelBuilder.Entity("MovieWorld.Models.User", b =>
                {
                    b.Navigation("Charts");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
