// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieWorld.Models;

public partial class ChartItem
{
    public int ChartId { get; set; }

    public int MovieId { get; set; }

    public int? Quantità { get; set; }

    public virtual Chart Chart { get; set; }

    public virtual Movie Movie { get; set; }
}