// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieWorld.Models;

public partial class Chart
{
    public int ChartId { get; set; }

    public int UserId { get; set; }

    public DateTime? CreationData { get; set; }

    public virtual ICollection<ChartItem> ChartItems { get; set; } = new List<ChartItem>();

    public virtual User User { get; set; }
}