// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieWorld.Models;

public partial class Format
{
    public int FormatId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Movie> Movies { get; set; } = new List<Movie>();
}