// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieWorld.Models;

public partial class LanguageCode
{
    public string LanguageCode1 { get; set; }

    public virtual ICollection<GenreTranslation> GenreTranslations { get; set; } = new List<GenreTranslation>();

    public virtual ICollection<MovieTranslation> MovieTranslations { get; set; } = new List<MovieTranslation>();

    public virtual ICollection<NewsTranslation> NewsTranslations { get; set; } = new List<NewsTranslation>();

    public virtual ICollection<SellPointTranslation> SellPointTranslations { get; set; } = new List<SellPointTranslation>();
}