// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieWorld.Models;

public partial class MovieTranslation
{
    public int MovieId { get; set; }

    public string LanguageCode { get; set; }

    public string Title { get; set; }

    public string Story { get; set; }

    public virtual LanguageCode LanguageCodeNavigation { get; set; }

    public virtual Movie Movie { get; set; }
}