// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieWorld.Models;

public partial class Movie
{
    public int MovieId { get; set; }

    public int FormatId { get; set; }

    public decimal? Cost { get; set; }

    public int? Year { get; set; }

    public string TrailerUrl { get; set; }

    public bool? IsCult { get; set; }

    public string ImagePath { get; set; }

    public virtual ICollection<ChartItem> ChartItems { get; set; } = new List<ChartItem>();

    public virtual Format Format { get; set; }

    public virtual ICollection<MoviePerson> MoviePeople { get; set; } = new List<MoviePerson>();

    public virtual ICollection<MovieSellPoint> MovieSellPoints { get; set; } = new List<MovieSellPoint>();

    public virtual ICollection<MovieTranslation> MovieTranslations { get; set; } = new List<MovieTranslation>();

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<News> News { get; set; } = new List<News>();

    public virtual ICollection<MovieGenre> MovieGenres { get; set; } = new List<MovieGenre>();
}