// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieWorld.Models;

public partial class MovieSellPoint
{
    public int MovieId { get; set; }

    public int SellPointId { get; set; }

    public int? Quantità { get; set; }

    public virtual Movie Movie { get; set; }

    public virtual SellPoint SellPoint { get; set; }
}