// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieWorld.Models;

public partial class News
{
    public int NewsId { get; set; }

    public string ImagePath { get; set; }

    public DateOnly? Date { get; set; }

    public virtual ICollection<NewsTranslation> NewsTranslations { get; set; } = new List<NewsTranslation>();

    public virtual ICollection<Movie> Movies { get; set; } = new List<Movie>();

    public virtual ICollection<Person> People { get; set; } = new List<Person>();
}