// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieWorld.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public DateTime? Date { get; set; }

    public int OrderStateId { get; set; }

    public int UserId { get; set; }

    public int SellPointId { get; set; }

    public string CouponCode { get; set; }

    public decimal DiscountAmount { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual OrderState OrderState { get; set; }

    public virtual SellPoint SellPoint { get; set; }

    public virtual User User { get; set; }
}