// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieWorld.Models;

public partial class OrderItem
{
    public int MovieId { get; set; }

    public int OrderId { get; set; }

    public int Quantity { get; set; }

    public decimal PurchasedPrice { get; set; }

    public virtual Movie Movie { get; set; }

    public virtual Order Order { get; set; }
}