// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieWorld.Models;

public partial class OrderState
{
    public int OrderStateId { get; set; }

    public virtual ICollection<OrderStateTranslation> OrderStateTranslations { get; set; } = new List<OrderStateTranslation>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}