// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieWorld.Models;

public partial class Person
{
    public int PersonId { get; set; }

    public string Name { get; set; }

    public string Surname { get; set; }

    public string ImagePath { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<MoviePerson> MoviePeople { get; set; } = new List<MoviePerson>();

    public virtual ICollection<News> News { get; set; } = new List<News>();
}