// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieWorld.Models;

public partial class SellPoint
{
    public int SellPointId { get; set; }

    public string Name { get; set; }

    public string Province { get; set; }

    public string Cap { get; set; }

    public double? Lat { get; set; }

    public double? Lng { get; set; }

    public virtual ICollection<MovieSellPoint> MovieSellPoints { get; set; } = new List<MovieSellPoint>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<SellPointTranslation> SellPointTranslations { get; set; } = new List<SellPointTranslation>();
}