// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieWorld.Models;

public partial class SellPointTranslation
{
    public int SellPointId { get; set; }

    public string LanguageCode { get; set; }

    public string Address { get; set; }

    public string Description { get; set; }

    public string City { get; set; }

    public virtual LanguageCode LanguageCodeNavigation { get; set; }

    public virtual SellPoint SellPoint { get; set; }
}