// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieWorld.Models;

public partial class User
{
    public int UserId { get; set; }

    public string Email { get; set; }

    public string HashPassword { get; set; }

    public string Name { get; set; }

    public string Surname { get; set; }

    public int Role { get; set; }

    public string ImagePath { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? PreferredSellPointId { get; set; }

    public bool EmailNotificationsEnabled { get; set; } = true;

    public virtual ICollection<Chart> Charts { get; set; } = new List<Chart>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual SellPoint PreferredSellPoint { get; set; }
}